--19120583 - BTVN11
USE QLDT
GO

--Câu 1:
CREATE PROCEDURE spPhanCong @magv char(5), @madt char(5), @stt int, @phucap float, @kq NVARCHAR(40)
AS
	--KIỂM TRA MÃ GIÁO VIÊN CÓ TỒN TẠI HAY KHÔNG
	IF(NOT EXISTS(SELECT MAGV FROM GiaoVien WHERE MAGV = @magv))
			RETURN -1
		
	--KIỂM TRA MÃ ĐỀ TÀI CÓ TỒN TAI HAY KHÔNG
	IF(NOT EXISTS(SELECT MADT FROM DeTai WHERE MADT = @madt))
		RETURN -2

	--KIỂM TRA GIÁO VIÊN ĐÃ THAM GIA ĐỦ 3 CÔNG VIỆC CỦA ĐỀ TÀI HAY CHƯA
	IF(EXISTS(SELECT MAGV
			FROM ThamGiaDT 
			WHERE MADT = @madt
			AND MAGV = @magv
			GROUP BY MAGV
			HAVING COUNT(MAGV) >= 3))
			RETURN -3

	--KIỂM TRA ĐỀ TÀI ĐÃ CÓ ĐỦ 3 GIÁO VIÊN THAM GIA CHƯA
	IF(EXISTS(SELECT MADT
			FROM ThamGiaDT 
			WHERE MADT = @madt
			GROUP BY MADT
			HAVING COUNT(DISTINCT MAGV) >= 3))
			RETURN -4

	--NẾU HỢP LỆ, THÊM DỮ LIỆU
	INSERT INTO ThamGiaDT(MAGV,MADT,STT,PHUCAP,KETQUA)
	VALUES 
		(@magv, @madt, @stt, @phucap, @kq)
	RETURN 1
GO

--TEST
DECLARE @MS CHAR(5), @MDT CHAR(3), @STT INT, @PC FLOAT, @KQ NVARCHAR(40)
SET @MS = '001'
SET @MDT = '006'
SET @STT = 1
SET @PC = 2.0
SET @KQ = N'ĐẠT'
DECLARE @ANS INT
EXEC @ANS = spPhanCong @MS, @MDT, @STT, @PC, @KQ
PRINT @ANS

SELECT * FROM ThamGiaDT
GO


--Câu 2:
CREATE PROC spXoaGV @magv CHAR(5)
AS
	--KIỂM TRA MÃ GIÁO VIÊN CÓ TỒN TẠI HAY KHÔNG
	IF(NOT EXISTS(SELECT MAGV FROM GiaoVien WHERE MAGV = @magv))
		BEGIN
			PRINT N'Giáo viên không tồn tại'
			RETURN -1
		END

	--KIỂM TRA CÓ PHẢI LÀ TRƯỞNG KHOA HAY KHÔNG
	if(EXISTS (SELECT * FROM Khoa K WHERE K.TRUONGKHOA = @magv)) --NẾU CÓ, CẬP NHẬT NULL
		UPDATE Khoa 
		SET TRUONGKHOA = NULL
		WHERE TRUONGKHOA = @magv

	--KIỂM TRA CÓ PHẢI LÀ TRƯỞNG BỘ MÔN HAY KHÔNG
	if(EXISTS (SELECT * FROM BoMon BM WHERE BM.TRUONGBM = @magv)) 
		UPDATE BoMon
		SET TRUONGBM = NULL
		WHERE TRUONGBM = @magv

	--KIỂM TRA CÓ PHẢI LÀ GIÁO VIÊN QLCM HAY KHÔNG
	if(EXISTS (SELECT * FROM GiaoVien GV WHERE GV.GVQLCM = @magv)) 
		UPDATE GiaoVien
		SET GVQLCM = NULL
		WHERE GVQLCM = @magv		

	--KIỂM TRA CÓ PHẢI LÀ GIÁO VIÊN  HAY KHÔNG
	if(EXISTS (SELECT * FROM DeTai DT WHERE DT.GVCNDT = @magv)) 
		UPDATE DeTai
		SET GVCNDT = NULL
		WHERE GVCNDT = @magv	

	--KIỂM TRA GV CÓ NGƯỜI THÂN HAY KHÔNG
	if(EXISTS (SELECT * FROM NguoiThan NT WHERE NT.MAGV = @magv)) 
		DELETE FROM NguoiThan
		WHERE MAGV = @magv

	--KIỂM TRA GV CÓ THAM GIA ĐỀ TÀI NÀO HAY KHÔNG
	if(EXISTS (SELECT * FROM ThamGiaDT TG WHERE TG.MAGV = @magv))
		DELETE FROM ThamGiaDT
		WHERE MAGV = @magv

	--KIỂM TRA CÓ PHẢI LÀ TRƯỞNG KHOA HAY KHÔNG
	if(EXISTS (SELECT * FROM GV_DT DT WHERE DT.MAGV = @magv))
		DELETE FROM GV_DT
		WHERE MAGV = @magv

	--XUẤT RA THÔNG BÁO SAU KHI ĐÃ KIỂM TRA CÁC ĐIỀU KIỆN
	PRINT N'Xóa thành công!'
	RETURN 1
GO

--TEST
DECLARE @MS char(5)
SET @MS = '001'
EXEC spXoaGV @MS
GO

--Câu 3
CREATE PROC spCapNhatTruongBM @magv char(5), @mabm char(5), @ngaync datetime
AS
	--KIỂM TRA MÃ GIÁO VIÊN CÓ TỒN TẠI HAY KHÔNG
	IF(NOT EXISTS(SELECT MAGV FROM GiaoVien WHERE MAGV = @magv))
			RETURN -1
		
	--KIỂM TRA MÃ BỘ MÔN CÓ TỒN TẠI HAY KHÔNG
	IF(NOT EXISTS(SELECT MABM FROM BoMon WHERE MABM = @mabm))
			RETURN -2

	--KIỂM TRA GIÁO VIÊN CÓ THUỘC BỘ MÔN MÌNH SẼ LÀM TRƯỞNG HAY KHÔNG
	IF(@mabm != (SELECT GV.MABM FROM GiaoVien GV WHERE GV.MAGV = @magv))
			RETURN -3

	--KIỂM TRA GIÁO VIÊN CÓ PHẢI TRƯỞNG KHOA HAY KHÔNG
	IF(EXISTS(SELECT TRUONGKHOA FROM Khoa WHERE TRUONGKHOA = @magv))
		RETURN -4

	--KIỂM TRA TUỔI CỦA GIÁO VIÊN
	DECLARE @TMP1 DATETIME, @TMP2 DATETIME
	SET @TMP1 = (SELECT NGSINH FROM GiaoVien WHERE MAGV = @magv)
	SET @TMP2 = GETDATE();
	IF(DATEDIFF(YEAR,@TMP1, @TMP2) <= 22) 
		RETURN -5

	--NẾU HỢP LỆ THÌ CẬP NHẬT
	UPDATE BoMon
	SET TRUONGBM = @magv
	WHERE MABM = @mabm

	UPDATE BoMon
	SET NGAYNHANCHUC = @ngaync
	WHERE TRUONGBM = @magv

	RETURN 1
GO

--TEST
DECLARE @MS CHAR(5), @MM CHAR(5), @NGAY DATETIME
SET @MS = '006'
SET @MM = 'VS'
SET @NGAY = '6/17/2021'
DECLARE @ANS INT
EXEC @ANS = spCapNhatTruongBM @MS,@MM,@NGAY
PRINT @ANS

SELECT * FROM BoMon
GO

--CÂU 4:
CREATE PROC spThemCongViec @MADT CHAR(3), @TEN NVARCHAR(40), @NGBD DATETIME, @NGKT DATETIME
AS
BEGIN
	DECLARE @isFailed INT
	SET @isFailed = 1
	--KIỂM TRA MÃ ĐỀ TÀI CÓ TỒN TAI HAY KHÔNG
	IF(NOT EXISTS(SELECT MADT FROM DeTai WHERE MADT = @madt))
		BEGIN
		PRINT N'ĐỀ TÀI KHÔNG TỒN TẠI!'
		SET @isFailed = 0
		END

	--KIỂM TRA NGÀY
	IF(DATEDIFF(DAY, @NGBD, @NGKT) <= 0)
		BEGIN
		PRINT N'NGÀY BẮT ĐẦU PHẢI NHỎ HƠN NGÀY KẾT THÚC!'
		SET @isFailed = 0
		END

	--KIỂM TRA NGÀY BẮT ĐẦU VỚI NGÀY HIỆN HÀNH
	DECLARE @NOW DATETIME
	SET @NOW = GETDATE()
	IF(DATEDIFF(DAY, @NOW, @NGBD) <= 0) 
		BEGIN
		PRINT N'NGÀY BẮT ĐẦU PHẢI LỚN HƠN NGÀY HIỆN HÀNH!'
		SET @isFailed = 0
		END

	--KIỂM TRA SỐ CÔNG VIỆC CỦA ĐỀ TÀI
	IF(EXISTS(SELECT MADT
			FROM CongViec
			WHERE MADT = @MADT
			GROUP BY MADT
			HAVING COUNT(MADT) >= 10))
		BEGIN
		PRINT N'VƯỢT QUÁ SỐ CÔNG VIỆC TỐI ĐA CHO ĐỀ TÀI'
		SET @isFailed = 0
		END
	
	--NẾU HỢP LỆ, THÊM THÔNG TIN VÀO CongViec
	IF(@isFailed = 1)
		BEGIN
			--LẤY STT LỚN NHẤT CỦA CÔNG VIỆC
			DECLARE @MAX_STT INT
			IF(NOT EXISTS (SELECT MADT
							FROM CongViec
							WHERE MADT = @MADT)) SET @MAX_STT = 1
			ELSE SET @MAX_STT = (SELECT MAX(SOTT)
							FROM CongViec
							WHERE MADT = @MADT) + 1
			--THÊM VÀO DATEBASE
			INSERT INTO CongViec(MADT, SOTT, TENCV, NGAYBD, NGAYKT)
			VALUES (@MADT, @MAX_STT, @TEN, @NGBD, @NGKT)

			PRINT N'THÊM THÀNH CÔNG'
		END
END
GO

--TEST
DECLARE @MDT CHAR(3), @TEN NVARCHAR(40), @NBD DATETIME, @NKT DATETIME
SET @MDT = '007'
SET @TEN = N'Khởi tạo và Lập kế hoạch'
SET @NBD = '6/21/2021'
SET @NKT = '7/12/2022'

EXEC spThemCongViec @MDT, @TEN, @NBD, @NKT
GO

SELECT * FROM CongViec

GO